name: Docker CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
 
env:
  NEXUS_URL: 4.186.30.35:8082
  REPO_NAME: docker-hosted-repo
  
    

jobs:
  build:
    name: Docker Build CI
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host  
        
      # - name: Nexus Login
      #   run: |
      #     docker login ${{ env.NEXUS_URL }} \
      #     -u "${{ secrets.NEXUS_USER }}" \
      #     -p "${{ secrets.NEXUS_PASS }}"



      - name: Nexus Login
        uses: docker/login-action@v4.0.0
        with:
          registry: ${{ env.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASS }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v7
        with:
          context: .
          # Path to the Dockerfile
          file: ./Dockerfile 
          push: true
          tags: ${{ env.NEXUS_URL }}/${{ env.REPO_NAME }}/react-app:${{ github.run_number }} 
         
         

          
          
          
          

    
      

          
        
