name: Docker CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NEXUS_URL: https://20.197.46.174:8082
   

jobs:
  build:
    name: Docker Build CI
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Build Docker Image
      #   run: docker build -t react-app:${{ github.run_number }} .

      - name: Trust Nexus SSL Certificate
        run: |
          echo "${{ secrets.NEXUS_CERT }}" > nexus.crt
          sudo cp nexus.crt /usr/local/share/ca-certificates/nexus.crt
          sudo update-ca-certificates


      - name: Login to Nexus
        run: |
          echo "${{ secrets.NEXUS_PASS }}" | docker login ${{ env.NEXUS_URL }} -u "${{ secrets.NEXUS_USER }}" --password-stdin

      - name: Tag Docker Image
        run: |
          docker tag react-app:${{ github.run_number }} ${{ env.NEXUS_URL }}/react-app:${{ github.run_number }}

      - name: Push Docker Image
        run: |
          docker push ${{ env.NEXUS_URL }}/react-app:${{ github.run_number }}

          
          

    
      

          
        
