name: Application CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
 

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.3.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16.x # optional

      - name: install dependencies
        run: npm install

      - name: build application
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: build/

        




          
      
