name: Application CI

# on:
#   workflow_dispatch: 
  # push:
  #   branches:
  #     - main
  #     - develop
  # pull_request:
  #   branches:
  #     - develop

env:
  NEXUS_URL: http://192.168.224.1:8081
  NEXUS_REPO: my-nexus-repo
  

jobs:
  build:
    name: Build Application
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16.x # optional

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}


      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'  #agar na mile cache to npm run chala dena else chala skip
        run: npm ci


      

      - name: build application
        run: npm run build
          

      # 🔢 Version generate (unique every build)
      - name: Set version
        run: |
          echo "VERSION=1.0.${{ github.run_number }}-${{ github.run_id }}" >> $GITHUB_ENV

      # 📦 Zip build folder (important for upload)
      - name: Zip build (faster)
        run: tar -a -c -f build.zip build

      # 📤 Upload to Nexus
      - name: Upload to Nexus
        run: |
          $pair = "${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }}"
          $encoded = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes($pair))
          
          Invoke-WebRequest `
            -Uri "http://192.168.224.1:8081/repository/my-nexus-repo/frontend-${{ env.VERSION }}.zip" `
            -Method Put `
            -InFile build.zip `
            -Headers @{ Authorization = "Basic $encoded" }

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: build/

         




          
      
